# Fichero de configuración para los contenedores del servidor de la aplicación Agenda
version: "3.8"
services:
  # Contenedor para el servidor laravel
  agenda-server:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: agenda-server
    ports:
      - 81:80
    networks:
      - agenda
    # Se mapea la carpeta con una local
    volumes:
      - .:/var/www/html/
    # TODO:descomentar para producción
    # restart: always

networks:
  agenda:
    driver: bridge
